#!/usr/bin/env bash
# this script displays Best School 10 times, but on the 9th iteration displays Hi as well

count=0

while [ $count -lt 10 ]
do
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( count++ ))
done	
